//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestRun
    {
        public LoadTestRun()
        {
            this.LoadTestCases = new HashSet<LoadTestCase>();
            this.LoadTestDataCollectorLogs = new HashSet<LoadTestDataCollectorLog>();
            this.LoadTestFileAttachments = new HashSet<LoadTestFileAttachment>();
            this.LoadTestFileAttachmentChunks = new HashSet<LoadTestFileAttachmentChunk>();
            this.LoadTestMessages = new HashSet<LoadTestMessage>();
            this.LoadTestPerformanceCounters = new HashSet<LoadTestPerformanceCounter>();
            this.LoadTestPerformanceCounterCategories = new HashSet<LoadTestPerformanceCounterCategory>();
            this.LoadTestPerformanceCounterInstances = new HashSet<LoadTestPerformanceCounterInstance>();
            this.LoadTestPerformanceCounterSamples = new HashSet<LoadTestPerformanceCounterSample>();
            this.LoadTestRunAgents = new HashSet<LoadTestRunAgent>();
            this.LoadTestRunIntervals = new HashSet<LoadTestRunInterval>();
            this.LoadTestSystemUnderTests = new HashSet<LoadTestSystemUnderTest>();
            this.LoadTestSystemUnderTestTags = new HashSet<LoadTestSystemUnderTestTag>();
            this.LoadTestScenarios = new HashSet<LoadTestScenario>();
            this.LoadTestSqlTraces = new HashSet<LoadTestSqlTrace>();
            this.LoadTestTestLogs = new HashSet<LoadTestTestLog>();
            this.LoadTestThresholdMessages = new HashSet<LoadTestThresholdMessage>();
            this.WebLoadTestErrorDetails = new HashSet<WebLoadTestErrorDetail>();
            this.WebLoadTestRequestMaps = new HashSet<WebLoadTestRequestMap>();
            this.WebLoadTestTransactions = new HashSet<WebLoadTestTransaction>();
        }
    
        public int LoadTestRunId { get; set; }
        public string LoadTestName { get; set; }
        public string RunId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int RunDuration { get; set; }
        public int WarmupTime { get; set; }
        public string RunSettingUsed { get; set; }
        public bool IsLocalRun { get; set; }
        public string ControllerName { get; set; }
        public string Outcome { get; set; }
        public byte[] LoadTest { get; set; }
        public string Comment { get; set; }
        public Nullable<int> LoadTestSchemaRev { get; set; }
        public Nullable<int> CooldownTime { get; set; }
    
        public virtual ICollection<LoadTestCase> LoadTestCases { get; set; }
        public virtual ICollection<LoadTestDataCollectorLog> LoadTestDataCollectorLogs { get; set; }
        public virtual ICollection<LoadTestFileAttachment> LoadTestFileAttachments { get; set; }
        public virtual ICollection<LoadTestFileAttachmentChunk> LoadTestFileAttachmentChunks { get; set; }
        public virtual ICollection<LoadTestMessage> LoadTestMessages { get; set; }
        public virtual ICollection<LoadTestPerformanceCounter> LoadTestPerformanceCounters { get; set; }
        public virtual ICollection<LoadTestPerformanceCounterCategory> LoadTestPerformanceCounterCategories { get; set; }
        public virtual ICollection<LoadTestPerformanceCounterInstance> LoadTestPerformanceCounterInstances { get; set; }
        public virtual ICollection<LoadTestPerformanceCounterSample> LoadTestPerformanceCounterSamples { get; set; }
        public virtual ICollection<LoadTestRunAgent> LoadTestRunAgents { get; set; }
        public virtual ICollection<LoadTestRunInterval> LoadTestRunIntervals { get; set; }
        public virtual ICollection<LoadTestSystemUnderTest> LoadTestSystemUnderTests { get; set; }
        public virtual ICollection<LoadTestSystemUnderTestTag> LoadTestSystemUnderTestTags { get; set; }
        public virtual ICollection<LoadTestScenario> LoadTestScenarios { get; set; }
        public virtual ICollection<LoadTestSqlTrace> LoadTestSqlTraces { get; set; }
        public virtual ICollection<LoadTestTestLog> LoadTestTestLogs { get; set; }
        public virtual ICollection<LoadTestThresholdMessage> LoadTestThresholdMessages { get; set; }
        public virtual ICollection<WebLoadTestErrorDetail> WebLoadTestErrorDetails { get; set; }
        public virtual ICollection<WebLoadTestRequestMap> WebLoadTestRequestMaps { get; set; }
        public virtual ICollection<WebLoadTestTransaction> WebLoadTestTransactions { get; set; }
    }
}
