//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestReport
    {
        public int ReportId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LoadTestName { get; set; }
        public int LastRunId { get; set; }
        public bool SelectNewRuns { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public byte ReportType { get; set; }
    }
}
