//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestMessageView2
    {
        public int LoadTestRunId { get; set; }
        public string AgentName { get; set; }
        public string ScenarioName { get; set; }
        public string TestCaseName { get; set; }
        public string RequestUri { get; set; }
        public int MessageId { get; set; }
        public System.DateTime MessageTimeStamp { get; set; }
        public byte MessageType { get; set; }
        public string SubType { get; set; }
        public string MessageText { get; set; }
        public string StackTrace { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string HasWebTestErrorDetail { get; set; }
        public Nullable<int> TestLogId { get; set; }
    }
}
