//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestTransactionDetail
    {
        public int LoadTestRunId { get; set; }
        public int TransactionDetailId { get; set; }
        public int TestDetailId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int TransactionId { get; set; }
        public double ElapsedTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> InMeasurementInterval { get; set; }
        public Nullable<double> ResponseTime { get; set; }
    }
}
