//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestPageDetail
    {
        public int LoadTestRunId { get; set; }
        public int PageDetailId { get; set; }
        public int TestDetailId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int PageId { get; set; }
        public double ResponseTime { get; set; }
        public double ResponseTimeGoal { get; set; }
        public bool GoalExceeded { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<byte> Outcome { get; set; }
        public Nullable<bool> InMeasurementInterval { get; set; }
    }
}
