//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestWebPageAndUserLoadCounterSample
    {
        public int loadtestrunid { get; set; }
        public string instanceName { get; set; }
        public string RequestUri { get; set; }
        public System.DateTime IntervalStartTime { get; set; }
        public Nullable<float> UserLoad { get; set; }
        public Nullable<float> ResponseTime { get; set; }
        public Nullable<float> RPS { get; set; }
    }
}
