//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestTransactionSummary
    {
        public string LoadTestName { get; set; }
        public int LoadTestRunId { get; set; }
        public string CounterName { get; set; }
        public string ScenarioName { get; set; }
        public string TestCaseName { get; set; }
        public string TransactionName { get; set; }
        public Nullable<float> CumulativeValue { get; set; }
    }
}
