//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestTestResult
    {
        public int LoadTestRunId { get; set; }
        public string ScenarioName { get; set; }
        public string TestCaseName { get; set; }
        public int TestsRun { get; set; }
        public double Minimum { get; set; }
        public double Average { get; set; }
        public Nullable<double> Percentile90 { get; set; }
        public Nullable<double> Percentile95 { get; set; }
        public double Maximum { get; set; }
    }
}
