//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestPerformanceCounter
    {
        public int LoadTestRunId { get; set; }
        public int CounterCategoryId { get; set; }
        public int CounterId { get; set; }
        public string CounterName { get; set; }
        public Nullable<bool> HigherIsBetter { get; set; }
    
        public virtual LoadTestRun LoadTestRun { get; set; }
    }
}
