//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestSqlTrace
    {
        public int LoadTestRunId { get; set; }
        public string TextData { get; set; }
        public Nullable<long> Duration { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<long> Reads { get; set; }
        public Nullable<long> Writes { get; set; }
        public Nullable<int> CPU { get; set; }
        public int EventClass { get; set; }
    
        public virtual LoadTestRun LoadTestRun { get; set; }
    }
}
