//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestComputedCounterSample
    {
        public int LoadTestRunId { get; set; }
        public string MachineName { get; set; }
        public string CategoryName { get; set; }
        public string CounterName { get; set; }
        public string InstanceName { get; set; }
        public System.DateTime IntervalStartTime { get; set; }
        public System.DateTime IntervalEndTime { get; set; }
        public int CounterType { get; set; }
        public Nullable<float> ComputedValue { get; set; }
        public long RawValue { get; set; }
        public byte ThresholdRuleResult { get; set; }
    }
}
