//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestComputedCounterSummary
    {
        public string LoadTestName { get; set; }
        public int LoadTestRunId { get; set; }
        public string MachineName { get; set; }
        public string CategoryName { get; set; }
        public string CounterName { get; set; }
        public Nullable<bool> HigherIsBetter { get; set; }
        public string InstanceName { get; set; }
        public Nullable<float> CumulativeValue { get; set; }
        public Nullable<byte> OverallThresholdRuleResult { get; set; }
    }
}
