//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelLoadTestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTestDataCollectorLog
    {
        public int LoadTestRunId { get; set; }
        public int DataCollectorLogId { get; set; }
        public string DataCollectorDisplayName { get; set; }
        public string MachineName { get; set; }
        public string TimestampColumnName { get; set; }
        public string DurationColumnName { get; set; }
        public string CreateTableFormatString { get; set; }
    
        public virtual LoadTestRun LoadTestRun { get; set; }
    }
}
